package net.microfalx.argus.api;

import net.microfalx.lang.service.Service;

import java.io.File;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.Optional;

/**
 * A service responsible to track log entries and report them.
 */
public interface LoggerService extends Service {

    static LoggerService getInstance() {
        return Service.lookup(LoggerService.class);
    }

    /**
     * Returns registered notification listeners.
     * <p>
     * The complete list is based on listeners discovered from class path and those registered
     * with {@link #register(LoggerListener)} .
     *
     * @return a non-null collection
     */
    Collection<LoggerListener> getListeners();

    /**
     * Return the logging directory, if enabled.
     * <p>
     * If the logging directory is not enabled, the file appenders are not created.
     *
     * @return a non-null instance
     */
    Optional<File> getDirectory();

    /**
     * Registers a listener.
     *
     * @param listener the listener
     */
    void register(LoggerListener listener);

    /**
     * Unregisters a listener.
     *
     * @param listener the listener
     */
    void unregister(LoggerListener listener);

    /**
     * Returns the alerts generated by loggers.
     *
     * @return a non-null instance
     */
    Collection<Alert> getAlerts();

    /**
     * Returns the application alerts for a given time interval.
     *
     * @param start the start time
     * @param end   the end time
     * @return a non-null instance
     */
    Collection<Alert> getAlerts(LocalDateTime start, LocalDateTime end);

    /**
     * Returns an alert by its identifier.
     *
     * @param id the alert identifier
     * @return the alert, null if it does not exist
     */
    Alert getAlert(String id);

    /**
     * Returns the last N configured logger events.
     *
     * @return a non-null instance
     */
    Collection<LoggerEvent> getLoggerEvents();

    /**
     * Registers the loggers.
     */
    void register();
}
